package com.xjtu.tdchaindemo.dao;

import com.xjtu.tdchaindemo.dataobject.TransactionDO;
import com.xjtu.tdchaindemo.dataobject.TransactionDOExample;

import java.util.List;
public interface TransactionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    long countByExample(TransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    int deleteByExample(TransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    int insert(TransactionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    int insertSelective(TransactionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    List<TransactionDO> selectByExample(TransactionDOExample example);

    List<TransactionDO> listTransaction();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    TransactionDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    int updateByPrimaryKeySelective(TransactionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    int updateByPrimaryKey(TransactionDO record);
}