package com.xjtu.tdchaindemo.dataobject;

public class TransactionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.id
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.name
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.hash
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.url
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.type
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.id
     *
     * @return the value of transaction.id
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.id
     *
     * @param id the value for transaction.id
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.name
     *
     * @return the value of transaction.name
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.name
     *
     * @param name the value for transaction.name
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.hash
     *
     * @return the value of transaction.hash
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.hash
     *
     * @param hash the value for transaction.hash
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.url
     *
     * @return the value of transaction.url
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.url
     *
     * @param url the value for transaction.url
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.type
     *
     * @return the value of transaction.type
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.type
     *
     * @param type the value for transaction.type
     *
     * @mbg.generated Thu Jun 10 20:56:26 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }
}